---
title: "Publications"
editor:
  markdown:
    wrap: 72
---

::: {.callout-note}
## Links

- **Google Scholar**: <https://scholar.google.com/citations?hl=en&user=1Wkzyd8AAAAJ&view_op=list_works&sortby=pubdate>
- **ORCID**: <https://orcid.org/0009-0004-5846-3216>
:::

## Publications

1. **Pan L**, Li C, Moog P, Knoedler S, Kükrek H, Dornseifer U, Machens H-G, Jiang J. Large-Scale Plasma Proteomics and Genetic Integration Uncover Novel Biological Pathways in Male Pattern Baldness. **International Journal of Molecular Sciences**. 2026;27(4):2052. doi: [10.3390/ijms27042052](https://doi.org/10.3390/ijms27042052).
2. Li C, **Pan L**. Overlooking Study Quality Undermines Conclusions: A Call for Rigorous Bias Assessment in Surgical Meta-analyses. **Aesthetic Plast Surg**. 2026 Jan 20. doi: [10.1007/s00266-026-05665-x](https://doi.org/10.1007/s00266-026-05665-x). Epub ahead of print. PMID: 41559391.
3. **Pan L**, Moog P, Li C, Steinbacher L, Knoedler S, Kukrek H, Dornseifer U, Machens H-G, Jiang J. Exploring the Association Between Multidimensional Dietary Patterns and Non-Scarring Hair Loss Using Mendelian Randomization. **Nutrients**. 2025;17(15):2569. doi: [10.3390/nu17152569](https://doi.org/10.3390/nu17152569).
4. **Pan L**, Li C. Comment on "Genetic and environmental factors affecting hair density in East Asian populations". **Br J Dermatol**. Published online June 18, 2025. doi: [10.1093/bjd/ljaf231](https://doi.org/10.1093/bjd/ljaf231).
5. Li C, Shen K, **Pan L**. Exploring the causal relationship between GLP-1R agonists and diseases related to the thyroid and parathyroid: a mendelian randomization study. **J Diabetes Metab Disord**. 2025;24(1):64.
6. **Pan L**, Li C. Comment on "An international multicenter, retrospective cohort study of 203 patients with pediatric androgenetic alopecia". **J Am Acad Dermatol**. Published online April 24, 2025.
7. **Pan L**, Li C. Exosome Therapy for Androgenetic Alopecia: Balancing Potential with Standardization Challenges. **Aesthetic Plast Surg**. Published online May 20, 2025.
8. **Pan L**, Li C, Liang Z, Shi J. Exploring the association between skin microbiota and inflammatory skin diseases: a two-sample Mendelian randomization analysis. **Arch Dermatol Res**. 2024;316(10):677.
9. **Pan L**, Zhang L, Fu J, Shen K, Zhang G. Integrated transcriptome sequencing and weighted gene co-expression network analysis reveals key genes of papillary thyroid carcinomas. **Heliyon**. 2024;10(7):e27928.
10. **Pan L**, Li C, Wang Z, Yang L, Zhang L. Preparation of an antibacterial dressing for simultaneous delivery of polyhexamethylene biguanide and platelet-rich plasma, and evaluation of the dressing's ability to promote infected skin repair. **Biochemical Engineering Journal**. 2022:108626.
11. **Pan L**, Qin H, Li C, Yang L, Li M, Kong J, et al. Safety and efficacy of botulinum toxin type A in preventing and treating scars in animal models: A systematic review and meta-analysis. **International Wound Journal**. 2021. doi: [10.1111/iwj.13673](https://doi.org/10.1111/iwj.13673).
12. **Pan L**, Qin H, Li C, Zhang G, Yang L, Zhang L. Efficacy of the Neodymium-Doped Yttrium Aluminum Garnet Laser in the Treatment of Keloid and Hypertrophic Scars: A Systematic Review and Meta-analysis. **Aesthetic Plast Surg**. 2022. doi: [10.1007/s00266-021-02716-3](https://doi.org/10.1007/s00266-021-02716-3).
13. Liang Z*, **Pan L**\\*, Shi J, Zhang L. C1QA, C1QB, and GZMB are novel prognostic biomarkers of skin cutaneous melanoma relating tumor microenvironment. **Sci Rep**. 2022;12:20460. doi: [10.1038/s41598-022-24353-9](https://doi.org/10.1038/s41598-022-24353-9).
14. Li C, **Pan L**, Yang L, Kong J, Zhang L. An umbrella review of the use of platelet-rich plasma in the treatment of androgenetic alopecia. **J Cosmet Dermatol**. 2023. doi: [10.1111/jocd.15617](https://doi.org/10.1111/jocd.15617).
15. Shi J, Liang Z, Liu Z, et al. Identification of Novel Proteins Mediating Causal Association Between Smoking and Essential Hypertension: A Mendelian Randomization Study. **J Am Heart Assoc**. 2024;13(23):e036202.
16. Shi J, Liu S, Guo Y, Liu S, Xu J, **Pan L**, et al. Association between eNOS rs1799983 polymorphism and hypertension: a meta-analysis involving 14,185 cases and 13,407 controls. **BMC Cardiovasc Disord**. 2021;21(1):385. doi: [10.1186/s12872-021-02192-2](https://doi.org/10.1186/s12872-021-02192-2).
17. Shi J, Guo Y, Li Z, Liang Z, **Pan L**, Yu Y, et al. Sociodemographic and behavioral influences on multimorbidity among adult residents of northeastern China. **BMC Public Health**. 2022;22(1):342. doi: [10.1186/s12889-022-12722-y](https://doi.org/10.1186/s12889-022-12722-y).
18. Shao A, Shi J, Liang Z, **Pan L**, Zhu W, Liu S, Xu J, Guo Y, Cheng Y, Qiao Y. Meta-analysis of the association between Apolipoprotein E polymorphism and risks of myocardial infarction. **BMC Cardiovasc Disord**. 2022 Mar 24;22(1):126. doi: [10.1186/s12872-022-02566-0](https://doi.org/10.1186/s12872-022-02566-0).
19. Yang L, **Pan L**, Qin H, Zhang L. Research progress of hypoxia-induced HIF-1 in pathological scars. **Chinese Journal of Aesthetic Plastic Surgery**. 2021;32(07):427-430.

